### ISSUE TITLE
Spurious space in titlepage.svg (in top Images folder)

### ISSUE THREAD

**Issue by drgrigg** [davgross/james-weldon-johnson_the-autobiography-of-an-ex-colored-man#1]
A very minor issue, but there's a spurious space before OF in the tilepage.svg title:

```
<text class="title" x="700" y="130">THE AUTOBIOGRAPHY</text>
<text class="title" x="700" y="230"> OF</text>
<text class="title" x="700" y="330">AN EX-COLORED MAN</text>
<text class="author" x="700" y="490">JAMES WELDON JOHNSON</text>
```

**Comment by davgross** [comment]
Hmmm... I don't think I touched this file after it was generated, so this may be a tooling issue.

**Comment by drgrigg** [comment]
I agree, I'll ask @acabal to look at it. I saw a similar effect in the last book I reviewed (which I can't now recall what it was!).
