### ISSUE TITLE
Need three-em dashes for completely obscured words

### ISSUE THREAD

**Issue by drgrigg** [davgross/james-weldon-johnson_the-autobiography-of-an-ex-colored-man#2]
The SE Style Manual specifies three-em dashes when a word is completely obscured. So in this passage (chapter 9):

`“What did you say?” “What does the word ⸺ mean?” “I understand all you say except ⸺.” “Please repeat.” “What do you call ⸺?” “How do you say ⸺?”`

It's probably not clear in the above, but I currently see them as two-em dashes in my useful font which distinguishes them.

**Comment by davgross** [comment]
I think you're right. This may be another tooling issue. I think I noted that the tool had changed these automatically and assumed that it had changed them to the correct dash variety, without checking for myself to be sure (they look about the same in my editor).
